fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: [--fix-only]
      - id: ruff-format
  - hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: pretty-format-json
        args: ["--autofix", "--indent=4"]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
